#Install Microsoft SQl Server for PHP
---
  - name: Download Remi Repo
    get_url: url=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm dest=/root/
    tags: php-fpm
  
  - name: Install Repo
    yum: name=/root/epel-release-latest-7.noarch.rpm state=present

  - name: Download Remi Repo
    get_url: url=https://rpms.remirepo.net/enterprise/remi-release-7.rpm dest=/root/
  
  - name: install php
    yum: name=/root/remi-release-7.rpm state=present
 

