---
  - name: Download Remi Repo
    get_url: url=http://rpms.remirepo.net/enterprise/remi-release-7.rpm dest=/root/
    tags: php-fpm

  - name: Install Repo
    yum: name=/root/remi-release-7.rpm state=present
   
  - name: install php
    yum: enablerepo=remi,remi-php74 name=php,php-common,php-opcache,php-mcrypt,php-cli,php-gd,php-curl,php-mysql,php-soap,php-ldap,php-mbstring,php-zip,php-xml state=latest

  - name: install php-fpm
    yum: enablerepo=remi,remi-php74 name=php-fpm state=latest
  
  - name: change php-fpm to listen on socket
    ini_file: dest=/etc/php-fpm.d/www.conf
              section=www
              option=listen
              value=/run/php-fpm/php-fpm.sock

  - name: php-fpm listen mode should always be 0666
    ini_file: dest=/etc/php-fpm.d/www.conf
            section=www
            option=listen.mode
            value=0666

  - name: change php-fpm user
    ini_file: dest=/etc/php-fpm.d/www.conf
              section=www
              option=user
              value=nginx

  - name: change php-fpm group
    ini_file: dest=/etc/php-fpm.d/www.conf
              section=www
              option=group
              value=nginx

  - name: change php-fpm group
    ini_file: dest=/etc/php-fpm.d/www.conf
              section=www
              option=listen.owner
              value=nginx


  - name: start php-fpm
    service: name=php-fpm state=started enabled=yes
    tags: php-fpm

  #- name: Change php.ini
   # ini_file: dest=/etc/php.ini
    #          section=Date
     #         option=date.timezone
      #        value=Etc/UTC
