---
 # Setup/install tasks.
 - include_tasks: CentOs7.yml
  #when: ansible_distribution == 'CentOS'
   when: ansible_os_family == 'RedHat'

 - include_tasks: Ubuntu.yml
   when: ansible_os_family == 'Debian'

