---
# tasks file for nginx
  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: Install nginx
    yum:
      name: nginx
      state: present

#  - name: Insert Index Page
 #   template:
  #    src: index.html
   #   dest: /usr/share/nginx/html/index.html

  - name: Start NGiNX
    service:
      name: nginx
      state: started
 
  - name: Create folder sites-available
    file:
      path: /etc/nginx/sites-available
      state: directory
      owner: root
      group: root
      mode: '0755'

  - name: Create folder sites-enabled
    file:
      path: /etc/nginx/sites-enabled
      state: directory
      owner: root
      group: root
      mode: '0755'

