---
  - name: Install Epel-Release
    yum: 
      name: epel-release
      state: present
  - name: Install Vim
    yum:
      name: vim
      state: present
  - name: Install HTOP
    yum:
      name: htop
      state: present





